# Generated by Django 4.2.3 on 2023-08-20 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verb", models.CharField(max_length=256, verbose_name="действие")),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время события"
                    ),
                ),
            ],
            options={
                "verbose_name": "действие",
                "verbose_name_plural": "действия",
                "ordering": ["-created"],
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["id"],
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True,
                default=users.models.get_default_profile_image,
                upload_to="avatars/",
                verbose_name="изображение профиля",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="отчество"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="телефон"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["id"], name="users_custo_id_b28d27_idx"),
        ),
        migrations.AddField(
            model_name="action",
            name="target_ct",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_obj",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="action",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
