# Generated by Django 4.2.3 on 2023-09-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_deliver_free_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="стоимость доставки",
            ),
        ),
    ]
