# Generated by Django 4.2.3 on 2023-09-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="price",
            new_name="delivery_price",
        ),
    ]
