# Generated by Django 4.2.3 on 2023-09-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_rename_price_order_delivery_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliver",
            name="is_express",
            field=models.BooleanField(default=False, verbose_name="экспресс доставка"),
        ),
    ]
