# Generated by Django 4.2.3 on 2023-07-27 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512, verbose_name="название")),
                (
                    "image",
                    models.FileField(
                        upload_to="categories/icons/", verbose_name="иконка (в SVG)"
                    ),
                ),
                (
                    "is_chosen",
                    models.BooleanField(default=False, verbose_name="избранный"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="удалён"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="products.category",
                        verbose_name="родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512, verbose_name="название")),
                ("description", models.TextField(blank=True)),
                (
                    "features",
                    models.JSONField(blank=True, verbose_name="характеристики"),
                ),
                (
                    "is_chosen",
                    models.BooleanField(default=False, verbose_name="избранный"),
                ),
                (
                    "is_limited",
                    models.BooleanField(default=False, verbose_name="ограниченный"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="удалён"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="название")),
            ],
            options={
                "verbose_name": "тэг",
                "verbose_name_plural": "тэги",
                "ordering": ["title"],
                "indexes": [
                    models.Index(fields=["title"], name="products_ta_title_af0455_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512, verbose_name="название")),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/products/", verbose_name="изображение"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="товар",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="products.tag",
                verbose_name="тэги",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["id"], name="products_pr_id_b46934_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["title"], name="products_pr_title_7d8124_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created"], name="products_pr_created_1360ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["title"], name="products_ca_title_80a91b_idx"),
        ),
    ]
