# Generated by Django 4.2.3 on 2023-08-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0002_alter_productimage_options_alter_category_is_chosen_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "priority",
                    models.PositiveIntegerField(default=0, verbose_name="приоритет"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("DP", "Процент скидки"),
                            ("DA", "Сумма скидки"),
                            ("FP", "Фиксированная стоимость"),
                        ],
                        default="DP",
                        max_length=2,
                        verbose_name="механизм скидки",
                    ),
                ),
                (
                    "discount_value",
                    models.PositiveIntegerField(
                        verbose_name="размер скидки (руб. или %)"
                    ),
                ),
                (
                    "date_start",
                    models.DateField(blank=True, null=True, verbose_name="дата начала"),
                ),
                (
                    "date_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата завершения"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="активно"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="создано"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="обновлено"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="offers",
                        to="products.category",
                        verbose_name="категории",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="offers",
                        to="products.product",
                        verbose_name="товары",
                    ),
                ),
            ],
        ),
    ]
