# Generated by Django 4.2.3 on 2023-08-07 20:40

from django.db import migrations, models

import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_offer"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdBanner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(default=products.models.get_default_image,
                                            upload_to="media/banners/", verbose_name="banners")),
                ("is_chosen", models.BooleanField(default=False, verbose_name="is chosen")),
                ("link", models.URLField(verbose_name="link")),
                ("title", models.TextField(verbose_name="title")),
                ("content", models.TextField(verbose_name="content")),
            ],
        ),
        migrations.AlterModelOptions(
            name="offer",
            options={"ordering": ["-created"], "verbose_name": "скидка", "verbose_name_plural": "скидки"},
        ),
        migrations.AlterField(
            model_name="offer",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="создана"),
        ),
        migrations.AlterField(
            model_name="offer",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="активна"),
        ),
        migrations.AlterField(
            model_name="offer",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="обновлена"),
        ),
    ]
