# Generated by Django 4.2.3 on 2023-08-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_review_alter_offer_options_alter_offer_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created"], "verbose_name": "Отзыв", "verbose_name_plural": "Отзывы"},
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["id"], name="products_re_id_ba39f3_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["-created"], name="products_re_created_9d856f_idx"),
        ),
    ]
