# Generated by Django 4.2.3 on 2023-08-13 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_adbanner_alter_offer_options_alter_offer_created_and_more"),
        ("products", "0006_alter_review_author"),
    ]

    operations = [
    ]
