# Generated by Django 4.2.3 on 2023-08-16 13:06

from django.db import migrations, models

import products.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_merge_20230813_1438"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adbanner",
            options={"verbose_name": "баннер", "verbose_name_plural": "баннеры"},
        ),
        migrations.AlterField(
            model_name="adbanner",
            name="content",
            field=models.TextField(verbose_name="контент"),
        ),
        migrations.AlterField(
            model_name="adbanner",
            name="image",
            field=models.ImageField(
                default=products.models.get_default_image,
                upload_to="media/banners/",
                verbose_name="баннер",
            ),
        ),
        migrations.AlterField(
            model_name="adbanner",
            name="is_chosen",
            field=models.BooleanField(default=False, verbose_name="активен"),
        ),
        migrations.AlterField(
            model_name="adbanner",
            name="link",
            field=models.URLField(verbose_name="ссылка"),
        ),
        migrations.AlterField(
            model_name="adbanner",
            name="title",
            field=models.TextField(verbose_name="название"),
        ),
    ]
