# Generated by Django 4.2.3 on 2023-08-16 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("products", "0008_alter_adbanner_options_alter_adbanner_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verb", models.CharField(max_length=256, verbose_name="действие")),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="время события"
                    ),
                ),
                (
                    "target_ct",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_obj",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "действие",
                "verbose_name_plural": "действия",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["-created"], name="products_ac_created_e5d98d_idx"
                    ),
                    models.Index(
                        fields=["target_ct", "target_id"],
                        name="products_ac_target__57e28c_idx",
                    ),
                ],
            },
        ),
    ]
