# Generated by Django 4.2.3 on 2023-08-21 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_adbanner_options_alter_adbanner_content_and_more"),
        ("products", "0008_seller_position"),
    ]

    operations = []
