# Generated by Django 4.2.3 on 2023-09-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_merge_20230821_0839"),
    ]

    operations = [
        migrations.AddField(
            model_name="productposition",
            name="free_shipping",
            field=models.BooleanField(default=False, verbose_name="Бесплатная доставка"),
        ),
    ]
